version: "3.8"
services:
  api:
    build: ./api
    ports:
      - 4000:3000
    volumes:
      - ./api/src:/app/src
      - ./types:/app/src
      - ./api/logs/dev:/app/logs

  api-tests:
    image: my-social-app-api
    volumes:
      - ./api/src:/app/src
      - ./api/coverage:/app/coverage
    command: npm test

  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - social-app:/data/db

volumes:
  social-app:
