version: "3.8"
services:
  api:
    build: ./api
    ports:
      - 4000:3000
    environment:
      app_db: mongodb://db/social-app
    volumes:
      - ./api/src:/app/src
      - ./api/logs/dev:/app/logs

  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - social-app:/data/db

volumes:
  social-app:
